name: auto-merge

on:
  push:
    branches: [ "dev" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "merge"
  merge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v4 
      #   with:
      #      ref: dev
      #      token: ${{ secrets.USERPASS }}
      # - run: |
      #     git config --global user.email "sdragonguo@163.com"
      #     git config --global user.name "rechard.guo"        
      #     git fetch
      #     git checkout -b main --track origin/main        
      #     git pull
      #     git merge dev
      #     git push origin main
      - name: auto merge       
        run: |
          git config --global user.email "sdragonguo@163.com"
          git config --global user.name "rechard.guo" 
          mkdir code
          cd code
          git clone https://${{ secrets.USERPASS }}@github.com/${{ github.repository }}.git
          cd github-action-practise

          git checkout main
          git merge dev
          git commit -m "github actionflow auto-merge"
          git push